version: '3.7'

services:
  django:
    container_name: magazine_django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./env/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: magazine_db
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=magazine_db

volumes:
  postgres_data:





